# Primo stage: usiamo un'immagine con git per clonare il repository
FROM alpine/git@sha256:832b1cd1a271509f3d5272a1a62d4cb2ab1a53426ebde1f6c2cb7349f907dc6f AS git-stage
WORKDIR /repo
RUN git clone https://github.com/pagopa/selfcare-infra.git

FROM mcr.microsoft.com/azure-cli@sha256:5ecf42d8362e25717b35c994aa714ed399be7b4e6f6c2df2ba3591b717598f76
COPY --from=git-stage /repo/selfcare-infra/src/core/resources /workspace/resources/resources
CMD ["/bin/sh", "-c", "/initAzurite.sh"]