# Primo stage: usiamo un'immagine con git per clonare il repository
FROM alpine/git@sha256:77418e6e7c7f434c4a98eaff04ef16840cf03649c881c03948e3e213923e3136 AS git-stage
WORKDIR /repo
RUN git clone https://github.com/pagopa/selfcare-infra.git

FROM mcr.microsoft.com/azure-cli@sha256:5ecf42d8362e25717b35c994aa714ed399be7b4e6f6c2df2ba3591b717598f76
COPY --from=git-stage /repo/selfcare-infra/src/core/resources /workspace/resources/resources
CMD ["/bin/sh", "-c", "/initAzurite.sh"]