# Primo stage: usiamo un'immagine con git per clonare il repository
FROM alpine/git@sha256:6f3b5029566da8e90b24945933dcd806be866b64b1e706f51828bf84faccf21b AS git-stage
WORKDIR /repo
RUN git clone https://github.com/pagopa/selfcare-infra.git

FROM mcr.microsoft.com/azure-cli@sha256:5ecf42d8362e25717b35c994aa714ed399be7b4e6f6c2df2ba3591b717598f76
COPY --from=git-stage /repo/selfcare-infra/src/core/resources /workspace/resources/resources
CMD ["/bin/sh", "-c", "/initAzurite.sh"]