quarkus.http.port=8080

quarkus.log.level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) trace_id=%X{trace_id} span_id=%X{span_id} - %s%e%n
quarkus.http.limits.max-form-attribute-size=4096

quarkus.mongodb.connection-string = ${MONGODB-CONNECTION-STRING}
quarkus.mongodb.database = selcMsCore

delegation-cdc.appinsights.connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING:InstrumentationKey=00000000-0000-0000-0000-000000000000}
delegation-cdc.table.name=${START_AT_TABLE_NAME:CdCStartAt}
delegation-cdc.storage.connection-string=${STORAGE_CONNECTION_STRING:}
delegation-cdc.storage-account-name=${AZURE_STORAGE_ACCOUNT_NAME:}
delegation-cdc.managed-identity-client-id=${AZURE_CLIENT_ID:}

delegation-cdc.retry.min-backoff=${DELEGATION-CDC-RETRY-MIN-BACKOFF:10}
delegation-cdc.retry.max-backoff=${DELEGATION-CDC-RETRY-MAX-BACKOFF:30}
delegation-cdc.retry=${DELEGATION-CDC-RETRY:3}

delegation-cdc.products.available=${PRODUCTS-AVAILABLE:prod-pagopa}

delegation-cdc.send-events.watch.enabled=${DELEGATION_CDC_SEND_EVENTS_WATCH_ENABLED:false}
quarkus.rest-client.event-hub.url=${EVENT_HUB_BASE_PATH:test}${EVENT_HUB_SC_DELEGATIONS_TOPIC:sc-delegations}
eventhub.rest-client.keyName=${SHARED_ACCESS_KEY_NAME:test}
eventhub.rest-client.key=${EVENTHUB-SC-DELEGATIONS-SELFCARE-WO-KEY-LC:test}

## Jacoco
%test.quarkus.jacoco.data-file=target/jacoco.exec
%test.quarkus.test.flat-class-path=true
