# Primo stage: usiamo un'immagine con git per clonare il repository
FROM bitnami/git AS git-stage
WORKDIR /repo
RUN git clone https://github.com/pagopa/selfcare.git

# https://mcr.microsoft.com/en-us/artifact/mar/azure-cli/tag/2.89.1-azurelinux3.0
FROM mcr.microsoft.com/azure-cli@sha256:f2e73db53c04ca82a675f1ecaa7051c42886932d45656789f90038673a42db9a
COPY --from=git-stage /repo/selfcare/infra/core/resources /workspace/resources/resources
CMD ["/bin/sh", "-c", "/initAzurite.sh"]
