auth:
  - changed-files:
      - any-glob-to-any-file: ["apps/auth/**", "infra/resources/*/auth.tf", "infra/resources/*/auth-*.tf", "infra/resources/*/auth_ms*.tf"]

document-ms:
  - changed-files:
      - any-glob-to-any-file:
          ["apps/document-ms/**", "infra/resources/document-ms/**"]

iam:
  - changed-files:
      - any-glob-to-any-file: ["apps/iam/**", "infra/resources/*/iam.tf"]

onboarding-cdc:
  - changed-files:
      - any-glob-to-any-file:
          ["apps/onboarding-cdc/**", "infra/resources/*/onboarding.tf"]

onboarding-functions:
  - changed-files:
      - any-glob-to-any-file:
          ["apps/onboarding-functions/**", "infra/resources/*/onboarding.tf", "infra/apps/onboarding-functions/**"]

onboarding-ms:
  - changed-files:
      - any-glob-to-any-file:
          ["apps/onboarding-ms/**", "infra/resources/*/onboarding.tf"]

product:
  - changed-files:
      - any-glob-to-any-file: ["apps/product/**", "infra/resources/*/product.tf"]

product-cdc:
  - changed-files:
      - any-glob-to-any-file:
          ["apps/product-cdc/**", "infra/resources/*/product.tf"]

webhook:
  - changed-files:
      - any-glob-to-any-file: ["apps/webhook/**", "infra/resources/*/webhook.tf"]

registry-proxy:
  - changed-files:
      - any-glob-to-any-file: ["apps/registry-proxy/**", "infra/resources/*/registry-proxy*.tf"]

onboarding-backend:
  - changed-files:
      - any-glob-to-any-file: ["apps/onboarding-backend/**", "infra/resources/*/onboarding_backend*.tf"]

hub-spid-login:
  - changed-files:
      - any-glob-to-any-file: ["infra/apps/hub_spid_login/**", "infra/resources/*/hub_spid_login.tf"]

namirial-sign:
  - changed-files:
      - any-glob-to-any-file: ["infra/apps/namirial-sign/**", "infra/resources/*/namirial-sign.tf"]

cucumber-sdk:
  - changed-files:
      - any-glob-to-any-file: ["libs/selfcare-cucumber-sdk/**"]

onboarding-sdk:
  - changed-files:
      - any-glob-to-any-file: ["libs/selfcare-onboarding-sdk-**"]

security-sdk:
  - changed-files:
      - any-glob-to-any-file: ["libs/selfcare-sdk-security/**"]

libs:
  - changed-files:
      - any-glob-to-any-file: ["libs/**"]

ops:
  - changed-files:
      - any-glob-to-any-file:
          [".github/**", "infra/**", ".identity/**", ".opex/**"]

docs:
  - changed-files:
      - any-glob-to-any-file: ["README.md", "**/README.md", "**.md"]

hotfix:
  - base-branch: ["releases/*"]
