repos:
  - repo: https://github.com/pagopa/dx
    rev: pre_commit_scripts@0.0.1
    hooks:
      - id: lock_modules
        exclude: ^.*/(_modules|modules|\.terraform)(/.*)?$
        # Configure the paths to your Terraform configurations
        files: infra/(apps|cert|commons|repository)

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
#      - id: terraform_tfsec
#        args:
#          - --hook-config=--retry-once-with-cleanup=true