version: '3.8'
services:

  mongodb:
    image: mongo:latest@sha256:bf41aa48a1cc0ccc8e6071236acfc428b7110ec2cf14b47c8961bc472e2c7c61
    ports:
      - '27017:27017'
    volumes:
      - "./src/test/resources/db:/docker-entrypoint-initdb.d"
    networks:
      - develop-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    ports:
      - "10000:10000"
    command: "azurite --blobHost 0.0.0.0 --inMemoryPersistence"
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCD9I1QhZT4gRjAAHEDPazjFIwtg==
    networks:
      - develop-network

  azure-cli:
    build:
      context: "../../."
      dockerfile: "apps/auth/src/test/resources/Dockerfile-azure-cli"
    depends_on:
      - azurite
    networks:
      - develop-network
    volumes:
      - "./src/test/resources/blobStorageInit/initAzurite.sh:/initAzurite.sh"
      - "./src/test/resources/blobStorageInit/products.json:/workspace/products.json"
    environment:
      - SELFCARE_INFRA_PRIVATE_ENV=dev

  mockserver:
    image: mockserver/mockserver@sha256:adec675a93253dcd503cda331dbc8c88383c1c79ceb2370ec9766ad3f010d255
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
      - MOCKSERVER_ENABLE_CORS_FOR_API="true"
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
    volumes:
      - "./src/test/resources/mock:/config"
    networks:
      - develop-network

  userms:
    image: ghcr.io/pagopa/selfcare-user-ms:latest@sha256:5668263162c5815c6d69e818217ac6e57c7ba06cc75bbdc0f963c3100899775e
    ports:
      - '8084:8080'
    env_file:
      - "./src/test/resources/userenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

  externalms:
    image: ghcr.io/pagopa/selfcare-external-api-backend:latest@sha256:c94052c54728ef97b91d14edd431856b8eff9442464d171200d82c609ac7218f
    ports:
      - '8082:8082'
    env_file:
      - "./src/test/resources/externalenv"
    networks:
      - develop-network

  institutionms:
    image: ghcr.io/pagopa/selfcare-institution-ms:latest@sha256:2f1b0f4ade34e56003a1c4366ea09ff307c2da959db05c97f1361a0526e96f85
    ports:
      - '8083:8083'
    env_file:
      - "./src/test/resources/institutionenv"
    networks:
      - develop-network
    depends_on:
      - mongodb

networks:
  develop-network:
    name: selfcare-develop-network