# Application configuration
quarkus.application.name=registry-proxy-runner
# Scheduler - runs every 6 hours (4 times a day): at 00:00, 06:00, 12:00, 18:00
# ======================== Schedulers ========================
scheduler.anac-index.cron=0 0 1/6 * * ? 
scheduler.ipa-index-aoo.cron=0 0 2/6 * * ?
scheduler.ipa-index-categories.cron=0 0 3/6 * * ?
scheduler.ipa-index-institution.cron=0 0 */6 * * ?
scheduler.ipa-index-uo.cron=0 0 4/6 * * ?
scheduler.ivass-index.cron=0 0 5/6 * * ?
# ======================== IPA Open Data REST clients ========================
quarkus.rest-client.ipa-open-data-institution.url=${IPA_OPEN_DATA_URL:https://indicepa.gov.it/ipa-dati/datastore/dump}${IPA_OPEN_DATA_INSTITUTION_ENDPOINT:/d09adf99-dc10-4349-8c53-27b1e5aa97b6}
quarkus.rest-client.ipa-open-data-institution.connect-timeout=${IPA_OPEN_DATA_CONNECT_TIMEOUT:30000}
quarkus.rest-client.ipa-open-data-institution.read-timeout=${IPA_OPEN_DATA_READ_TIMEOUT:60000}
quarkus.rest-client.ipa-open-data-categories.url=${IPA_OPEN_DATA_URL:https://indicepa.gov.it/ipa-dati/datastore/dump}${IPA_OPEN_DATA_CATEGORY_ENDPOINT:/84ebb2e7-0e61-427b-a1dd-ab8bb2a84f07}
quarkus.rest-client.ipa-open-data-categories.connect-timeout=${IPA_OPEN_DATA_CONNECT_TIMEOUT:30000}
quarkus.rest-client.ipa-open-data-categories.read-timeout=${IPA_OPEN_DATA_READ_TIMEOUT:60000}
quarkus.rest-client.ipa-open-data-aoo.url=${IPA_OPEN_DATA_URL:https://indicepa.gov.it/ipa-dati/datastore/dump}${IPA_OPEN_DATA_AOO_ENDPOINT:/cdaded04-f84e-4193-a720-47d6d5f422aa}
quarkus.rest-client.ipa-open-data-aoo.connect-timeout=${IPA_OPEN_DATA_CONNECT_TIMEOUT:30000}
quarkus.rest-client.ipa-open-data-aoo.read-timeout=${IPA_OPEN_DATA_READ_TIMEOUT:60000}
quarkus.rest-client.ipa-open-data-uo.url=${IPA_OPEN_DATA_URL:https://indicepa.gov.it/ipa-dati/datastore/dump}${IPA_OPEN_DATA_UO_ENDPOINT:/b0aa1f6c-f135-4c8a-b416-396fed4e1a5d}
quarkus.rest-client.ipa-open-data-uo.connect-timeout=${IPA_OPEN_DATA_CONNECT_TIMEOUT:30000}
quarkus.rest-client.ipa-open-data-uo.read-timeout=${IPA_OPEN_DATA_READ_TIMEOUT:60000}
quarkus.rest-client.ipa-open-data-uo-sfe.url=${IPA_OPEN_DATA_URL:https://indicepa.gov.it/ipa-dati/datastore/dump}${IPA_OPEN_DATA_UO_SFE_ENDPOINT:/57bd2be0-4d3d-41cd-bdb8-2f0a60d6f490}
quarkus.rest-client.ipa-open-data-uo-sfe.connect-timeout=${IPA_OPEN_DATA_CONNECT_TIMEOUT:30000}
quarkus.rest-client.ipa-open-data-uo-sfe.read-timeout=${IPA_OPEN_DATA_READ_TIMEOUT:60000}
# ======================== ANAC REST client ========================
quarkus.rest-client.anac.url=${ANAC_BASE_URL:https://dati.anticorruzione.it}${ANAC_DATA_PATH:/opendata/dataset/anac-gestori}
quarkus.rest-client.anac.connect-timeout=${ANAC_CONNECT_TIMEOUT:30000}
quarkus.rest-client.anac.read-timeout=${ANAC_READ_TIMEOUT:60000}
# ======================== IVASS REST client ========================
quarkus.rest-client.ivass.url=${IVASS_BASE_URL:https://www.ivass.it}${IVASS_DATA_PATH:/RIGAInquiry-public/getAreaDownloadExport.do?referenceDate=&product=VFLUSSO_IMPRESE&language=IT&exportType=CSV&isCompressed=S}
quarkus.rest-client.ivass.connect-timeout=${IVASS_CONNECT_TIMEOUT:30000}
quarkus.rest-client.ivass.read-timeout=${IVASS_READ_TIMEOUT:60000}
ivass.registry-types-admitted=${IVASS_REGISTRY_TYPES:ElencoI,ElencoII,SezioneI,SezioneII}
ivass.work-types-admitted=${IVASS_WORK_TYPES:VITA,PICCOLO CUMULO,MISTA}
# ======================== Azure AI Search REST client ========================
quarkus.rest-client.azure-ai-search.url=${AZURE_SEARCH_BASE_URL:https://your-search-service.search.windows.net}
quarkus.rest-client.azure-ai-search.connect-timeout=${AZURE_SEARCH_CONNECT_TIMEOUT:5000}
quarkus.rest-client.azure-ai-search.read-timeout=${AZURE_SEARCH_READ_TIMEOUT:30000}
quarkus.rest-client.azure-ai-search.providers=it.pagopa.selfcare.registry.proxy.runner.client.AzureSearchHeadersFactory
azure-ai-search.api-key=${AZURE_SEARCH_API_KEY:}
azure-ai-search.api-version=${AZURE_SEARCH_API_VERSION:2023-11-01}
azure-ai-search.institution.index-name=${AZURE_SEARCH_IPA_INSTITUTION_INDEX:ipa-institution-index-ar}
azure-ai-search.aoo.index-name=${AZURE_SEARCH_IPA_AOO_INDEX:ipa-aoo-index-ar}
azure-ai-search.uo.index-name=${AZURE_SEARCH_IPA_UO_INDEX:ipa-uo-index-ar}
azure-ai-search.category.index-name=${AZURE_SEARCH_IPA_CATEGORY_INDEX:ipa-category-index-ar}
azure-ai-search.station.index-name=${AZURE_SEARCH_STATION_INDEX:station-index-ar}
azure-ai-search.insurance-company.index-name=${AZURE_SEARCH_INSURANCE_COMPANY_INDEX:insurance-company-index-ar}
# ======================== Azure REST client LOG ========================
quarkus.rest-client.logging.scope=all
quarkus.rest-client.logging.body-limit=51200
quarkus.log.category."io.quarkus.rest.client.logging".level=DEBUG
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
# Logging
quarkus.log.level=INFO
quarkus.log.category."it.pagopa.selfcare".level=DEBUG
