---
openapi: 3.0.3
tags:
- name: OIDC
- name: OTP
- name: SAML
components:
  schemas:
    Date:
      format: date
      type: string
      example: 2022-03-10
    MailStatusHistory:
      type: object
      properties:
        status:
          type: string
        changedAt:
          $ref: "#/components/schemas/OffsetDateTime"
    ObjectId:
      type: object
      properties:
        timestamp:
          format: int32
          type: integer
        nonce:
          format: int64
          type: integer
        date:
          $ref: "#/components/schemas/Date"
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    OidcExchangeOtpResponse:
      type: object
      properties:
        requiresOtpFlow:
          type: boolean
        otpSessionUid:
          type: string
        maskedEmail:
          type: string
    OidcExchangeRequest:
      required:
      - code
      - redirectUri
      type: object
      properties:
        code:
          minLength: 1
          type: string
        redirectUri:
          minLength: 1
          type: string
    OidcExchangeTokenResponse:
      type: object
      properties:
        sessionToken:
          type: string
        requiresOtpFlow:
          type: boolean
    OtpFlow:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ObjectId"
        uuid:
          type: string
        userId:
          type: string
        tenantId:
          type: string
        otp:
          type: string
        status:
          $ref: "#/components/schemas/OtpStatus"
        attempts:
          format: int32
          type: integer
        createdAt:
          $ref: "#/components/schemas/OffsetDateTime"
        updatedAt:
          $ref: "#/components/schemas/OffsetDateTime"
        expiresAt:
          $ref: "#/components/schemas/OffsetDateTime"
        mailRequestId:
          type: string
    OtpForbidden:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
        status:
          format: int32
          type: integer
        title:
          type: string
        type:
          type: string
        otpForbiddenCode:
          $ref: "#/components/schemas/OtpForbiddenCode"
        remainingAttempts:
          format: int32
          type: integer
        otpStatus:
          $ref: "#/components/schemas/OtpStatus"
    OtpForbiddenCode:
      enum:
      - CODE_001
      - CODE_002
      type: string
    OtpMailInfoResponse:
      type: object
      properties:
        mailRequestId:
          type: string
        status:
          type: string
        recipient:
          type: string
        attempts:
          format: int32
          type: integer
        history:
          type: array
          items:
            $ref: "#/components/schemas/MailStatusHistory"
    OtpResendRequest:
      required:
      - otpUuid
      type: object
      properties:
        otpUuid:
          minLength: 1
          type: string
    OtpStatus:
      enum:
      - PENDING
      - EXPIRED
      - REJECTED
      - COMPLETED
      type: string
    OtpVerifyRequest:
      required:
      - otpUuid
      - otp
      type: object
      properties:
        otpUuid:
          minLength: 1
          type: string
        otp:
          minLength: 1
          type: string
    Problem:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
        status:
          format: int32
          type: integer
        title:
          type: string
        type:
          type: string
    TokenResponse:
      type: object
      properties:
        sessionToken:
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication
paths:
  /oidc/exchange:
    post:
      summary: OIDC exchange endpoint
      description: OIDC exchange endpoint provides a token exchange by accepting a
        valid authorization code and releasing a jwt session token
      operationId: oidcExchange
      tags:
      - OIDC
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OidcExchangeRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OidcExchangeTokenResponse"
        "201":
          description: Created
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OidcExchangeOtpResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /otp/info:
    get:
      summary: Get OTP information
      description: Retrieve OTP information for a user
      operationId: getOtpInfo
      tags:
      - OTP
      parameters:
      - name: status
        in: query
        schema:
          $ref: "#/components/schemas/OtpStatus"
      - name: userId
        in: query
        schema:
          pattern: \S
          type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OtpFlow"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /otp/mail-info/{mailRequestId}:
    get:
      summary: Get OTP mail information
      description: Retrieve the processing status of an email managed by OneMail
      operationId: getOtpMailInfo
      tags:
      - OTP
      parameters:
      - name: mailRequestId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OtpMailInfoResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
  /otp/resend:
    post:
      summary: Resend OTP endpoint
      description: Resend an OTP if email has not been received by user
      operationId: otpResend
      tags:
      - OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OtpResendRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OidcExchangeOtpResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "409":
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /otp/verify:
    post:
      summary: Verify OTP endpoint
      description: Verify endpoint is used to complete an otp flow by validating user
        account
      operationId: otpVerify
      tags:
      - OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OtpVerifyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OtpForbidden"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "409":
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /saml/acs:
    post:
      summary: Login SAML endpoint
      description: Login SAML endpoint provides a token exchange releasing a jwt session
        token
      operationId: loginSaml
      tags:
      - SAML
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                SAMLResponse:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema: {}
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
info:
  title: Auth API
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
