---
openapi: 3.1.0
tags:
- name: OIDC
- name: OTP
- name: SAML
components:
  schemas:
    OidcExchangeOtpResponse:
      type: object
      properties:
        requiresOtpFlow:
          type: boolean
        otpSessionUid:
          type: string
        maskedEmail:
          type: string
    OidcExchangeRequest:
      type: object
      required:
      - code
      - redirectUri
      properties:
        code:
          type: string
          minLength: 1
        redirectUri:
          type: string
          minLength: 1
    OidcExchangeTokenResponse:
      type: object
      properties:
        sessionToken:
          type: string
        requiresOtpFlow:
          type: boolean
    OtpForbidden:
      type: object
      properties:
        otpForbiddenCode:
          $ref: "#/components/schemas/OtpForbiddenCode"
        remainingAttempts:
          type: integer
          format: int32
        otpStatus:
          $ref: "#/components/schemas/OtpStatus"
    OtpForbiddenCode:
      type: string
      enum:
      - CODE_001
      - CODE_002
    OtpResendRequest:
      type: object
      required:
      - otpUuid
      properties:
        otpUuid:
          type: string
          minLength: 1
    OtpStatus:
      type: string
      enum:
      - PENDING
      - EXPIRED
      - REJECTED
      - COMPLETED
    OtpVerifyRequest:
      type: object
      required:
      - otpUuid
      - otp
      properties:
        otpUuid:
          type: string
          minLength: 1
        otp:
          type: string
          minLength: 1
    Problem:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
        status:
          type: integer
          format: int32
        title:
          type: string
        type:
          type: string
    TokenResponse:
      type: object
      properties:
        sessionToken:
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication
paths:
  /oidc/exchange:
    post:
      summary: OIDC exchange endpoint
      description: OIDC exchange endpoint provides a token exchange by accepting a
        valid authorization code and releasing a jwt session token
      operationId: oidcExchange
      tags:
      - OIDC
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OidcExchangeRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OidcExchangeTokenResponse"
        "201":
          description: Created
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OidcExchangeOtpResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /otp/resend:
    post:
      summary: Resend OTP endpoint
      description: Resend an OTP if email has not been received by user
      operationId: otpResend
      tags:
      - OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OtpResendRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OidcExchangeOtpResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "409":
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /otp/verify:
    post:
      summary: Verify OTP endpoint
      description: Verify endpoint is used to complete an otp flow by validating user
        account
      operationId: otpVerify
      tags:
      - OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OtpVerifyRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/OtpForbidden"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "409":
          description: Conflict
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /saml/acs:
    post:
      summary: Login SAML endpoint
      description: Login SAML endpoint provides a token exchange releasing a jwt session
        token
      operationId: loginSaml
      tags:
      - SAML
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                SAMLResponse:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema: {}
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
info:
  title: Auth API
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
