user-group.allowed.sorting.parameters=${ALLOWED_SORTING_PARAMETERS:name}
spring.data.mongodb.uri=${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_NAME:selcUserGroup}

## INTERNAL EVENTS
user-group-ms.internalevents.connection-string=${INTERNALEVENTS_CONNECTION_STRING:}
user-group-ms.internalevents.namespace=${INTERNALEVENTS_NAMESPACE:}
user-group-ms.internalevents.client-id=${INTERNALEVENTS_CLIENT_ID:}
user-group-ms.internalevents.enabled=${INTERNALEVENTS_ENABLED:false}
