user-group.allowed.sorting.parameters=${ALLOWED_SORTING_PARAMETERS:name}
spring.data.mongodb.uri=${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_NAME:selcUserGroup}
tenant.mongodb.enabled=${TENANT_MONGODB_ENABLED:true}
tenant.storage.enabled=${TENANT_STORAGE_ENABLED:true}
tenant.supported-tenants=${TENANT_SUPPORTED_TENANTS:AR}
tenant.default=${TENANT_DEFAULT:AR}
tenant.strict-data-isolation=${TENANT_STRICT_DATA_ISOLATION:true}
tenant.storage.mandatory-keys=${TENANT_STORAGE_MANDATORY_KEYS:}
tenant.registry.json=${SELFCARE_TENANT_DATA_ISOLATION:{"AR":{"mongo":{"account":"local","database":"selcUserGroup","connectionStringEnvVar":"spring.data.mongodb.uri"},"jwt":{"publicKeyEnvVar":"jwt.signingKey"},"storages":{}}}}

## INTERNAL EVENTS
user-group-ms.internalevents.connection-string=${INTERNALEVENTS_CONNECTION_STRING:}
user-group-ms.internalevents.namespace=${INTERNALEVENTS_NAMESPACE:}
user-group-ms.internalevents.client-id=${INTERNALEVENTS_CLIENT_ID:}
user-group-ms.internalevents.enabled=${INTERNALEVENTS_ENABLED:false}
