services:

  mongodb:
    platform: linux/amd64
    image: mongo@sha256:406a4fdca9fc763443268f000218d3849ef8996f66ed9e92ba0b501b446ab822
    ports:
      - '27017:27017'
    volumes:
      - "./src/test/resources/db:/docker-entrypoint-initdb.d"
    networks:
      - developer-network

  # https://mcr.microsoft.com/en-us/artifact/mar/azure-storage/azurite/tags
  azurite:
    platform: linux/amd64
    image: mcr.microsoft.com/azure-storage/azurite@sha256:d5bb99496dc82ef0e34401ced6726d2f5d8fcbdf48670ba067ee3b394884cc3a
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - developer-network
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCD9I1QhZT4gRjAAHEDPazjFIwtg==
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --inMemoryPersistence --skipApiVersionCheck"

  # https://mcr.microsoft.com/en-us/artifact/mar/azure-cli/tags
  azure-cli:
    image: mcr.microsoft.com/azure-cli@sha256:d483c14775d67577de4b2887aaef6d88f5a5371a151ad59872be91602cd89635
    depends_on:
      - azurite
    volumes:
      - "./src/test/resources/blobStorageInit/init_azurite.sh:/init_azurite.sh"
      - "./src/test/resources/blobStorageInit/products.json:/workspace/products.json"
    environment:
      - SELFCARE_INFRA_PRIVATE_ENV=dev
    networks:
      - developer-network
    command: [ "/bin/sh", "-c", "/init_azurite.sh" ]

  mock-server:
    platform: linux/amd64
    image: mockserver/mockserver@sha256:adec675a93253dcd503cda331dbc8c88383c1c79ceb2370ec9766ad3f010d255
    ports:
      - "1080:1080"
    networks:
      - developer-network
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
      - MOCKSERVER_ENABLE_CORS_FOR_API="true"
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
    volumes:
      - "./mock:/config"

  institutionms:
    platform: linux/amd64
    image: ghcr.io/pagopa/selfcare-institution-ms:latest
    ports:
      - "8082:8082"
    networks:
      - developer-network
    env_file:
      - ./src/test/resources/test-institution-ms.env
    depends_on:
      mongodb:
        condition: service_started
      azure-cli:
        condition: service_completed_successfully
      mock-server:
        condition: service_started

  userms:
    platform: linux/amd64
    image: ghcr.io/pagopa/selfcare-user-ms:latest
    ports:
      - "8087:8087"
    env_file:
      - src/test/resources/test-user-ms.env
    networks:
      - developer-network
    depends_on:
      mongodb:
        condition: service_started
      azure-cli:
        condition: service_completed_successfully
      mock-server:
        condition: service_started

networks:
  developer-network:
    name: selfcare-iam-develop-network

secrets:
  maven_settings:
    file: ~/.m2/settings.xml
