package it.pagopa.selfcare.onboarding.parity;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * The OpenAPI documents committed under src/main/docs (regenerated by the build) must declare the
 * contract of the Spring public specification. Necessary, not sufficient: the behaviour is proven
 * by the parity scenarios.
 */
class PublishedOpenApiGateTest {

  static final Path PUBLISHED_JSON = Path.of("src/main/docs/openapi.json");
  static final Path PUBLISHED_YAML = Path.of("src/main/docs/openapi.yaml");

  private static JsonNode published() throws IOException {
    return new ObjectMapper().readTree(Files.readAllBytes(PUBLISHED_JSON));
  }

  @Test
  void publishedDocsDeclareTheSameContractAsSpring() throws IOException {
    OpenApiGate.assertSameContract(published());
  }

  @Test
  void publishedDocsDeclareTheSameErrorResponsesAsSpring() throws IOException {
    OpenApiGate.assertSameErrorResponses(published());
  }

  @Test
  void yamlAndJsonDocsAreTheSameDocument() throws IOException {
    JsonNode yaml = new ObjectMapper(new YAMLFactory()).readTree(Files.readAllBytes(PUBLISHED_YAML));

    assertEquals(published(), yaml);
  }
}
