quarkus.http.port=${B4F_ONBOARDING_SERVER_PORT:8080}
quarkus.log.level=TRACE
quarkus.log.category."it.pagopa.selfcare".level=${B4F_ONBOARDING_LOG_LEVEL:DEBUG}
quarkus.http.limits.max-body-size=10M
quarkus.smallrye-openapi.info-title=@project.artifactId@
quarkus.smallrye-openapi.info-version=@project.version@
quarkus.smallrye-openapi.info-description=@project.description@
quarkus.smallrye-openapi.store-schema-directory=src/main/docs

mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
smallrye.jwt.claims.sub=uid
quarkus.http.auth.proactive=false

# App Insights
onboarding-bff.appinsights.connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING:InstrumentationKey=00000000-0000-0000-0000-000000000000}

user-allowed-list=${USER_ALLOWED_LIST:null}

quarkus.openapi-generator.codegen.validateSpec=false
quarkus.openapi-generator.codegen.spec.institution_json.mutiny=true
quarkus.openapi-generator.codegen.spec.institution_json.enable-security-generation=false
quarkus.openapi-generator.codegen.spec.institution_json.additional-api-type-annotations=@org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders(it.pagopa.selfcare.onboarding.security.AuthenticationPropagationHeadersFactory.class)

quarkus.openapi-generator.codegen.spec.onboarding_json.mutiny=true
quarkus.openapi-generator.codegen.spec.onboarding_json.enable-security-generation=false
quarkus.openapi-generator.codegen.spec.onboarding_json.additional-api-type-annotations=@org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders(it.pagopa.selfcare.onboarding.security.AuthenticationPropagationHeadersFactory.class)

quarkus.openapi-generator.codegen.spec.user_registry_json.mutiny=true
quarkus.openapi-generator.user_registry_json.auth.api_key.api-key=${USER-REGISTRY-API-KEY:example-api-key}

quarkus.openapi-generator.codegen.spec.user_json.mutiny=true
quarkus.openapi-generator.codegen.spec.user_json.enable-security-generation=false
quarkus.openapi-generator.codegen.spec.user_json.additional-api-type-annotations=@org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders(it.pagopa.selfcare.onboarding.security.AuthenticationPropagationHeadersFactory.class)

quarkus.openapi-generator.codegen.spec.onboarding_functions_json.mutiny=true
quarkus.openapi-generator.onboarding_functions_json.auth.api_key.api-key=${ONBOARDING-FUNCTIONS-API-KEY:example-api-key}

quarkus.openapi-generator.codegen.spec.product_json.mutiny=true
quarkus.openapi-generator.codegen.spec.product_json.enable-security-generation=false
quarkus.openapi-generator.codegen.spec.product_json.additional-api-type-annotations=@org.eclipse.microprofile.rest.client.annotation.RegisterClientHeaders(it.pagopa.selfcare.onboarding.security.AuthenticationPropagationHeadersFactory.class)

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=50

# Rest client base URLs
rest-client.ms-onboarding.base-url=${MS_ONBOARDING_URL:http://10.1.1.250:80/ms-onboarding/v1}
rest-client.ms-user.base-url=${MS_USER_URL:http://localhost:8080}
rest-client.ms-product.base-url=${MS_PRODUCT_URL:http://localhost:8080}
rest-client.ms-core.base-url=${MS_CORE_URL:http://10.1.1.250:80/ms-core/v1}
rest-client.party-process.base-url=${USERVICE_PARTY_PROCESS_URL:http://localhost:8080/pdnd-interop-uservice-party-process/0.0.1}
rest-client.party-registry-proxy.base-url=${USERVICE_PARTY_REGISTRY_PROXY_URL:http://localhost:8080/external/ur/v1}
rest-client.user-registry.base-url=${USERVICE_USER_REGISTRY_URL:http://localhost:8080/pdnd-interop-uservice-user-registry/0.0.1}

quarkus.rest-client.onboarding_json.url=${rest-client.ms-onboarding.base-url}
quarkus.rest-client.user_json.url=${rest-client.ms-user.base-url}
quarkus.rest-client.product_json.url=${rest-client.ms-product.base-url}
quarkus.rest-client.institution_json.url=${rest-client.ms-core.base-url}
quarkus.rest-client.onboarding_functions_json.url=${ONBOARDING_FUNCTIONS_URL:https://localhost:8080}
quarkus.rest-client.user_registry_json.url=${rest-client.user-registry.base-url}

quarkus.rest-client.ms_core.url=${rest-client.ms-core.base-url}
quarkus.rest-client.party_process.url=${rest-client.party-process.base-url}
quarkus.rest-client.party_registry_proxy.url=${rest-client.party-registry-proxy.base-url}

# Product SDK
onboarding-bff.blob-storage.container-product=${PRODUCT_STORAGE_CONTAINER:selc-d-product}
onboarding-bff.blob-storage.filepath-product=products.json
onboarding-bff.blob-storage.connection-string-product=${BLOB_STORAGE_PRODUCT_CONNECTION_STRING:UseDevelopmentStorage=true;}
