quarkus.http.port=8080

quarkus.log.level=INFO
quarkus.http.limits.max-form-attribute-size=4096

quarkus.mongodb.connection-string = ${MONGODB-CONNECTION-STRING}
quarkus.mongodb.database = selcMsCore

institution-cdc.table.name=${START_AT_TABLE_NAME:CdCStartAt}
institution-cdc.storage.connection-string=${STORAGE_CONNECTION_STRING:}
institution-cdc.storage-account-name=${AZURE_STORAGE_ACCOUNT_NAME:}
institution-cdc.managed-identity-client-id=${AZURE_CLIENT_ID:}
