---
openapi: 3.1.0
tags:
- name: IAM
components:
  schemas:
    Problem:
      type: object
      properties:
        detail:
          type: string
        instance:
          type: string
        status:
          type: integer
          format: int32
        title:
          type: string
        type:
          type: string
    SaveUserRequest:
      type: object
      required:
      - email
      properties:
        email:
          type: string
          minLength: 1
        name:
          type: string
        familyName:
          type: string
        roles:
          type: array
          items:
            type: string
  securitySchemes:
    SecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication
paths:
  /iam/ping:
    get:
      summary: Ping endpoint
      operationId: ping
      tags:
      - IAM
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
  /iam/users:
    patch:
      operationId: users
      tags:
      - IAM
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SaveUserRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/problem+json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
      summary: Users
info:
  title: IAM API
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
