on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tf_environment:
        type: string
        required: false
      dir:
        type: string
        required: true
      env_vars:
        type: string
        required: false
        description: List of environment variables to set up, given in env=value format.

env:
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true
  ARM_STORAGE_USE_AZUREAD: true
  TERRAFORM_ENVIRONMENT: ${{ inputs.tf_environment || inputs.environment }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  plan:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: "[${{ inputs.environment }}-${{ inputs.domain }}] ${{ inputs.app }} Infra Plan"
    with:
      environment: ${{ inputs.tf_environment }}
      base_path: ${{ inputs.dir }}
      env_vars: ${{ inputs.env_vars }}
      use_private_agent: true
      use_labels: true
      override_labels: ${{ inputs.environment }}