name: Deploy Selfcare App

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: Environment
        required: true
      target:
        type: string
        description: Target type
        required: true
      app:
        type: string
        description: App name
        required: true
      APP_PATH:
        type: string
        description: App Path
        required: true
      INFRA_PATH:
        type: string
        description: Infrastructure Path
        required: true
      APPS_POM:
        type: string
        description: Apps pom module path
        required: true
      POM:
        type: string
        description: Parent pom
        required: true

env:
  APP_PATH: 'apps/${{ inputs.app }}'
  INFRA_PATH: 'infra/apps/${{ inputs.app }}'
  APPS_POM: "apps/pom.xml"
  POM: "pom.xml"

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: ${{ inputs.target == 'selc' && '[Dev]' || '[Dev-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: ${{ inputs.target == 'selc' && 'dev' || 'dev-pnpg' }}
      dir: ${{ inputs.INFRA_PATH }}
      dockerfile_path: ./${{ inputs.APP_PATH }}/Dockerfile
      docker_image_name: pagopa/selfcare-${{ inputs.app }}-ms
      path_openapi_docs: ./${{ inputs.APP_PATH }}/src/main/docs/openapi.json

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: ${{ inputs.target == 'selc' && '[Uat]' || '[Uat-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: ${{ inputs.target == 'selc' && 'uat' || 'uat-pnpg' }}
      dir: ${{ inputs.INFRA_PATH }}
      dockerfile_path: ./${{ inputs.APP_PATH }}/Dockerfile
      docker_image_name: pagopa/selfcare-${{ inputs.app }}-ms
      path_openapi_docs: ./${{ inputs.APP_PATH }}/src/main/docs/openapi.json

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: ${{ inputs.target == 'selc' && '[Prod]' || '[Prod-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: ${{ inputs.target == 'selc' && 'prod' || 'prod-pnpg' }}
      dir: ${{ inputs.INFRA_PATH }}
      dockerfile_path: ./${{ inputs.APP_PATH }}/Dockerfile
      docker_image_name: pagopa/selfcare-${{ inputs.app }}-ms
      path_openapi_docs: ./${{ inputs.APP_PATH }}/src/main/docs/openapi.json
