name: Update GitHub Variable

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      env:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - name: Update Variable
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_VARIABLES }}
          INPUT_DOMAIN: ${{ inputs.domain }}
          INPUT_ENV: ${{ inputs.env }}
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_REPO: ${{ github.repository }}
        run: |
          VAR_DOMAIN=$(echo "$INPUT_DOMAIN" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
          VAR_ENV=$(echo "$INPUT_ENV" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
          VAR_NAME="${VAR_DOMAIN}_CURRENT_${VAR_ENV}_VERSION"

          echo "Updating variable $VAR_NAME to $INPUT_VERSION in repo $INPUT_REPO"
          gh variable set "$VAR_NAME" --body "$INPUT_VERSION" --repo "$INPUT_REPO"
