name: Deploy Functions App

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: Environment
        required: true
      target:
        type: string
        description: Target type
        required: true
      app:
        type: string
        description: Function name
        required: true

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:

#  infra_dev:
#    name: ${{ inputs.target == 'selc' && '[Dev]' || '[Dev-PNPG]' }} - Infra Apply
#    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
#    uses: ./.github/workflows/call_release_infra.yml
#    secrets: inherit
#    with:
#      environment: dev
#      tf_environment: ${{ inputs.target == 'selc' && 'dev-ar' || 'dev-pnpg' }}
#      dir: ${{ inputs.target == 'selc' && 'infra/resources/onboarding-functions/dev-ar' || 'infra/resources/onboarding-functions/dev-pnpg' }}

  release_dev:
    name: ${{ inputs.target == 'selc' && '[Dev]' || '[Dev-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
#    needs: [infra_dev]
    runs-on: ubuntu-24.04
    environment:
      name: dev-cd
      url: ${{ format('https://selc-{0}-onboarding-fn.azurewebsites.net', inputs.target == 'selc' && 'd' || 'd-pnpg') }}
    permissions:
      id-token: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4 # v1.11.0
        with:
          java-version: 17
          java-distribution: 'temurin'
          maven-version: '3.9.5'
          cache-enabled: true
      - name: Build & Deploy
        shell: bash
        run: |
          mvn --projects :${{ inputs.app }} --also-make package install -DskipTests \
            -Dquarkus.azure-functions.app-name=${{ format('selc-{0}-onboarding-fn', inputs.target == 'selc' && 'd' || 'd-pnpg') }}
      - name: Cloud Login
        uses: pagopa/dx/actions/csp-login@main
      - name: Deploy Function App
        shell: bash
        working-directory: apps/${{ inputs.app }}
        run: |
          mvn -f pom.xml quarkus:deploy \
            -Dquarkus.azure-functions.app-name=${{ format('selc-{0}-onboarding-fn', inputs.target == 'selc' && 'd' || 'd-pnpg') }} \
            -Dquarkus.azure-functions.subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }} \
            -Dquarkus.azure-functions.resource-group=${{ format('selc-{0}-onboarding-fn-rg', inputs.target == 'selc' && 'd' || 'd-pnpg') }} \
            -Dquarkus.azure-functions.region=westeurope \
            -Dquarkus.azure-functions.app-service-plan-name=${{ format('selc-{0}-onboarding-fn-plan', inputs.target == 'selc' && 'd' || 'd-pnpg') }} \
            -Dquarkus.azure-functions.runtime.java-version=17

  infra_uat:
    name: ${{ inputs.target == 'selc' && '[Uat]' || '[Uat-PNPG]' }} - Infra Apply
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    uses: ./.github/workflows/call_release_infra.yml
    secrets: inherit
    with:
      environment: uat
      tf_environment: ${{ inputs.target == 'selc' && 'uat-ar' || 'uat-pnpg' }}
      dir: ${{ inputs.target == 'selc' && 'infra/resources/onboarding-functions/uat-ar' || 'infra/resources/onboarding-functions/uat-pnpg' }}

  release_uat:
    name: ${{ inputs.target == 'selc' && '[Uat]' || '[Uat-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    needs: [infra_uat]
    runs-on: ubuntu-24.04
    environment:
      name: uat-cd
      url: ${{ format('https://selc-{0}-onboarding-fn.azurewebsites.net', inputs.target == 'selc' && 'u' || 'u-pnpg') }}
    permissions:
      id-token: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4 # v1.11.0
        with:
          java-version: 17
          java-distribution: 'temurin'
          maven-version: '3.9.5'
          cache-enabled: true
      - name: Build & Deploy
        shell: bash
        run: |
          mvn --projects :${{ inputs.app }} --also-make package install -DskipTests \
            -Dquarkus.azure-functions.app-name=${{ format('selc-{0}-onboarding-fn', inputs.target == 'selc' && 'u' || 'u-pnpg') }}
      - name: Cloud Login
        uses: pagopa/dx/actions/csp-login@main
      - name: Deploy Function App
        shell: bash
        working-directory: apps/${{ inputs.app }}
        run: |
          mvn -f pom.xml quarkus:deploy \
            -Dquarkus.azure-functions.app-name=${{ format('selc-{0}-onboarding-fn', inputs.target == 'selc' && 'u' || 'u-pnpg') }} \
            -Dquarkus.azure-functions.subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }} \
            -Dquarkus.azure-functions.resource-group=${{ format('selc-{0}-onboarding-fn-rg', inputs.target == 'selc' && 'u' || 'u-pnpg') }} \
            -Dquarkus.azure-functions.region=westeurope \
            -Dquarkus.azure-functions.app-service-plan-name=${{ format('selc-{0}-onboarding-fn-plan', inputs.target == 'selc' && 'u' || 'u-pnpg') }} \
            -Dquarkus.azure-functions.runtime.java-version=17

  infra_prod:
    name: ${{ inputs.target == 'selc' && '[Prod]' || '[Prod-PNPG]' }} - Infra Apply
    if: ${{ inputs.env == 'prod' }}
    uses: ./.github/workflows/call_release_infra.yml
    secrets: inherit
    with:
      environment: prod
      tf_environment: ${{ inputs.target == 'selc' && 'prod-ar' || 'prod-pnpg' }}
      dir: ${{ inputs.target == 'selc' && 'infra/resources/onboarding-functions/prod-ar' || 'infra/resources/onboarding-functions/prod-pnpg' }}

  release_prod:
    name: ${{ inputs.target == 'selc' && '[Prod]' || '[Prod-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ inputs.env == 'prod' }}
    needs: [infra_prod]
    runs-on: ubuntu-24.04
    environment:
      name: prod-cd
      url: ${{ format('https://selc-{0}-onboarding-fn.azurewebsites.net', inputs.target == 'selc' && 'p' || 'p-pnpg') }}
    permissions:
      id-token: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4 # v1.11.0
        with:
          java-version: 17
          java-distribution: 'temurin'
          maven-version: '3.9.5'
          cache-enabled: true
      - name: Build & Deploy
        shell: bash
        run: |
          mvn --projects :${{ inputs.app }} --also-make package install -DskipTests \
            -Dquarkus.azure-functions.app-name=${{ format('selc-{0}-onboarding-fn', inputs.target == 'selc' && 'p' || 'p-pnpg') }}
      - name: Cloud Login
        uses: pagopa/dx/actions/csp-login@main
      - name: Deploy Function App
        shell: bash
        working-directory: apps/${{ inputs.app }}
        run: |
          mvn -f pom.xml quarkus:deploy \
            -Dquarkus.azure-functions.app-name=${{ format('selc-{0}-onboarding-fn', inputs.target == 'selc' && 'p' || 'p-pnpg') }} \
            -Dquarkus.azure-functions.subscription-id=${{ secrets.ARM_SUBSCRIPTION_ID }} \
            -Dquarkus.azure-functions.resource-group=${{ format('selc-{0}-onboarding-fn-rg', inputs.target == 'selc' && 'p' || 'p-pnpg') }} \
            -Dquarkus.azure-functions.region=westeurope \
            -Dquarkus.azure-functions.app-service-plan-name=${{ format('selc-{0}-onboarding-fn-plan', inputs.target == 'selc' && 'p' || 'p-pnpg') }} \
            -Dquarkus.azure-functions.runtime.java-version=17
