name: Deploy Selfcare App

on:
  workflow_call:
    inputs:
      env:
        type: string
        description: Environment
        required: true
      target:
        type: string
        description: Target type
        required: true
      app:
        type: string
        description: App name
        required: true
      APP_PATH:
        type: string
        description: App Path
        required: true
      APPS_POM:
        type: string
        description: Apps pom module path
        required: true
      POM:
        type: string
        description: Parent pom
        required: true

env:
  APP_PATH: 'apps/${{ inputs.app }}'
  APPS_POM: "apps/pom.xml"
  POM: "pom.xml"

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_docker.yml
    name: ${{ inputs.target == 'selc' && '[Dev]' || '[Dev-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      app: ${{ inputs.app }}
      environment: dev
      tf_environment: ${{ inputs.target == 'selc' && 'dev-ar' || 'dev-pnpg' }}
      tf_dir: ${{ inputs.target == 'selc' && format('infra/resources/{0}/dev-ar', inputs.app) || format('infra/resources/{0}/dev-pnpg', inputs.app) }}
      dockerfile_path: ./${{ inputs.APP_PATH }}/Dockerfile
      docker_image_name: ${{ inputs.app == 'onboarding-bff' && format('pagopa/selfcare-{0}', inputs.app) || endsWith(inputs.app, '-cdc') && format('pagopa/selfcare-{0}', inputs.app) || endsWith(inputs.app, '-ms')  && format('pagopa/selfcare-{0}', inputs.app) || format('pagopa/selfcare-{0}-ms', inputs.app) }}
      path_openapi_docs: ${{ endsWith(inputs.app, '-bff') && format('./{0}/app/src/main/docs/openapi.json', inputs.APP_PATH) || format('./{0}/src/main/docs/openapi.json', inputs.APP_PATH) }}
      upload_openapi_enabled: ${{ inputs.target == 'selc' && !endsWith(inputs.app, '-cdc') }}

  release_uat:
    uses: ./.github/workflows/call_release_docker.yml
    name: ${{ inputs.target == 'selc' && '[Uat]' || '[Uat-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      app: ${{ inputs.app }}
      environment: uat
      tf_environment: ${{ inputs.target == 'selc' && 'uat-ar' || 'uat-pnpg' }}
      tf_dir: ${{ inputs.target == 'selc' && format('infra/resources/{0}/uat-ar', inputs.app) || format('infra/resources/{0}/uat-pnpg', inputs.app) }}
      dockerfile_path: ./${{ inputs.APP_PATH }}/Dockerfile
      docker_image_name: ${{ inputs.app == 'onboarding-bff' && format('pagopa/selfcare-{0}', inputs.app) || endsWith(inputs.app, '-cdc') && format('pagopa/selfcare-{0}', inputs.app) || endsWith(inputs.app, '-ms')  && format('pagopa/selfcare-{0}', inputs.app) || format('pagopa/selfcare-{0}-ms', inputs.app) }}
      path_openapi_docs: ${{ endsWith(inputs.app, '-bff') && format('./{0}/app/src/main/docs/openapi.json', inputs.APP_PATH) || format('./{0}/src/main/docs/openapi.json', inputs.APP_PATH) }}
      upload_openapi_enabled: ${{ inputs.target == 'selc' && !endsWith(inputs.app, '-cdc') }}

  release_prod:
    uses: ./.github/workflows/call_release_docker.yml
    name: ${{ inputs.target == 'selc' && '[Prod]' || '[Prod-PNPG]' }} - ${{ inputs.app }} Release
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      app: ${{ inputs.app }}
      environment: prod
      tf_environment: ${{ inputs.target == 'selc' && 'prod-ar' || 'prod-pnpg' }}
      tf_dir: ${{ inputs.target == 'selc' && format('infra/resources/{0}/prod-ar', inputs.app) || format('infra/resources/{0}/prod-pnpg', inputs.app) }}
      dockerfile_path: ./${{ inputs.APP_PATH }}/Dockerfile
      docker_image_name: ${{ inputs.app == 'onboarding-bff' && format('pagopa/selfcare-{0}', inputs.app) || endsWith(inputs.app, '-cdc') && format('pagopa/selfcare-{0}', inputs.app) || endsWith(inputs.app, '-ms')  && format('pagopa/selfcare-{0}', inputs.app) || format('pagopa/selfcare-{0}-ms', inputs.app) }}
      path_openapi_docs: ${{ endsWith(inputs.app, '-bff') && format('./{0}/app/src/main/docs/openapi.json', inputs.APP_PATH) || format('./{0}/src/main/docs/openapi.json', inputs.APP_PATH) }}
      upload_openapi_enabled: ${{ inputs.target == 'selc' && !endsWith(inputs.app, '-cdc') }}
