name: Drift Detection
run-name: Drift Detection (${{ inputs.environment }} - ${{ inputs.base_path }})

on:
  workflow_call:
    inputs:
      environment:
        description: Environment where the resources will be deployed.
        type: string
        required: true
        default: prod
      base_path:
        description: The base path on which the script will look for Terraform projects
        type: string
        required: true
        default: infra/resources/
      use_private_agent:
        description: Use a private agent to run the Terraform plan.
        type: boolean
        required: false
        default: false
      override_github_environment:
        description: Set a value if GitHub Environment name is different than the TF environment folder
        type: string
        required: false
        default: ""
      use_labels:
        description: Use labels to start the right environment's GitHub runner. If use_labels is true, also use_private_agent must be set to true
        type: boolean
        required: false
        default: false
      override_labels:
        description: Needed for special cases where the environment alone is not sufficient as a distinguishing label
        type: string
        required: false
        default: ""

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read
  id-token: write
  actions: read


jobs:
  drift_detection:
    uses: pagopa/dx/.github/workflows/infra_drift_detection.yml@main
    name: "[${{ inputs.env }}-${{ inputs.domain }}] Selfcare Infra Core Drift detection"
    secrets: inherit
    with:
      environment: ${{ inputs.env }}-${{ inputs.domain }}
      base_path: infra/core
      # env_vars: ""
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}  