name: Integration Tests - User Group MS

on:
  workflow_dispatch:

  schedule:
    - cron: '00 08 * * *'

  push:
    branches:
      - main
      - releases/**
    paths:
      - 'apps/user-group-ms/**'
      - 'libs/user-sdk-**/**'

jobs:
  integration_test:
    name: Integration Test User Group MS
    runs-on: ubuntu-22.04
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Run Integration Tests
        working-directory: apps/user-group-ms
        run: mvn clean verify -Pintegration-test
