name: Code Review functions infra

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - releases/**
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'infra/apps/onboarding-functions/**'
      - './.github/workflows/onboarding_pr_functions_infra.yml'
      - './.github/workflows/onboarding_call_code_review_infra.yml'

jobs:
  code_review_dev:
    uses: ./.github/workflows/onboarding_call_code_review_infra.yml
    name: '[DEV] Functions Infra Code Review'
    if: ${{ !startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: dev
      dir: infra/apps/onboarding-functions

  code_review_uat:
    uses: ./.github/workflows/onboarding_call_code_review_infra.yml
    name: '[UAT] Functions Infra Code Review'
    secrets: inherit
    with:
      environment: uat
      dir: infra/apps/onboarding-functions

  code_review_prod:
    uses: ./.github/workflows/onboarding_call_code_review_infra.yml
    name: '[PROD] Functions Infra Code Review'
    secrets: inherit
    with:
      environment: prod
      dir: infra/apps/onboarding-functions
