name: Core Code Review Infra DX

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ./infra/core/**
      - ./.github/workflows/call_code_review_infra_dx.yml
      - ./.github/workflows/pr_core_infra.yml

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: 'Select the Environment'
        default: dev
        options:
          - dev
          - uat
          - prod
      domain:
        required: true
        type: choice
        description: 'Select the Domain'
        default: ar
        options:
          - ar
          - pnpg

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read


# jobs:
#   plan:
#     uses: ./.github/workflows/call_code_review_infra_dx.yml
#     name: Core Code Review
#     secrets: inherit
#     with:
#       environment: ${{ inputs.environment }}
#       dir: './infra/core/${{ inputs.environment }}-${{ inputs.domain }}'
#       agent: self-hosted

jobs:
  infra_plan:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Infra plan
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      base_path: './infra/core/${{ inputs.environment }}-${{ inputs.domain }}'
      # Optional parameters
      env_vars: ""
      use_private_agent: true
      # override_github_environment: pe-prod
      use_labels: true
      override_labels: ""