name: Code Review - Onboarding Infra

permissions:
  contents: read
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - releases/*
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'infra/resources/**/onboarding.tf'
      - '.github/workflows/pr_onboarding_infra.yml'
      - '.github/workflows/call_code_review_infra.yml'

jobs:
  code_review_dev_ar:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[DEV-AR] Onboarding Infra Code Review'
    if: ${{ !startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: dev
      dir: ./infra/resources/dev-ar
      tf_environment: dev-ar
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  code_review_dev_pnpg:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[DEV-PNPG] Resources Infra Code Review'
    if: ${{ !startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: dev
      dir: ./infra/resources/dev-pnpg
      tf_environment: dev-pnpg
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  code_review_uat_ar:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[UAT-AR] Resources Infra Code Review'
    if: ${{ startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: uat
      dir: ./infra/resources/uat-ar
      tf_environment: uat-ar
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  code_review_uat_pnpg:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[UAT-PNPG] Resources Infra Code Review'
    if: ${{ startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: uat
      dir: ./infra/resources/uat-pnpg
      tf_environment: uat-pnpg
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  code_review_prod_ar:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[PROD-AR] Resources Infra Code Review'
    if: ${{ startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: prod
      dir: ./infra/resources/prod-ar
      tf_environment: prod-ar
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  code_review_prod_pnpg:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[PROD-PNPG] Resources Infra Code Review'
    if: ${{ startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: prod
      dir: ./infra/resources/prod-pnpg
      tf_environment: prod-pnpg
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})
