name: Code Review - Onboarding BFF

permissions:
  contents: read
  id-token: write
  packages: read
  pull-requests: write

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - releases/**
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "apps/onboarding-bff/**"
      - ".github/workflows/pr_onboarding_bff.yml"
      - ".github/workflows/call_code_review.yml"
      - ".github/workflows/call_openapi_verification.yml"

jobs:
  code_review:
    permissions:
      contents: read
      packages: read
      pull-requests: write
    uses: ./.github/workflows/call_code_review.yml
    name: "Onboarding BFF - Code Review"
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      source_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}
      sonar_key: "pagopa_selfcare"
      module: "onboarding-bff"

  openapi_check:
    needs: [code_review]
    permissions: write-all
    uses: ./.github/workflows/call_openapi_verification.yml
    name: Onboarding BFF OpenAPI Check
    secrets: inherit
    with:
      module: "onboarding-bff"
      path_openapi_docs: "apps/onboarding-bff/app/src/main/docs/openapi.json"
