name: Code Review - Onboarding BFF

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - releases/**
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "apps/onboarding-bff/**"
      - ".github/workflows/pr_onboarding_bff.yml"
      - ".github/workflows/call_code_review.yml"
      - ".github/workflows/integration_tests_onboarding_bff.yml"

jobs:
  code_review:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/call_code_review.yml
    name: "Onboarding BFF - Code Review"
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      source_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}
      sonar_key: "pagopa_selfcare-onboarding-backend"
      module: "onboarding-bff"
