name: Publish - Identity Bootstrap - Identity

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - 'infra/bootstrap/**'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod

jobs:
  release_dev_ar:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: '[Dev] Identity Bootstrap Infra Release (AR)'
    if: ${{ ((startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev') }}
    secrets: inherit
    with:
      environment: dev-ar
      base_path: infra/bootstrap
      # env_vars: ""
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}
    
  release_uat_ar:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: '[UAT] Identity Bootstrap Infra Release (AR)'
    if: ${{ ((startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat') }}
    secrets: inherit
    with:
      environment: uat-ar 
      base_path: infra/bootstrap
      # env_vars: ""
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}

  release_prod_ar:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: '[Prod] Identity Bootstrap Infra Release (AR)'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod-ar
      base_path: infra/bootstrap
      # env_vars: ""
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}

  
