name: Publish static assets

permissions:
  id-token: write
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - main
      - SELC-9240
    paths:
      - "infra/core/static/**"

  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: 'Select the Environment'
        default: 'dev'
        options:
        - dev
        - uat
        - prod
      domain:
        required: true
        type: choice
        description: 'Select the Domain'
        default: 'ar'
        options:
        - ar
        - pnpg

concurrency:
  group: publish-static-${{ inputs.domain || 'ar' }}-${{ inputs.env || 'dev' }}
  cancel-in-progress: false

jobs:
  release_dev:
    uses: ./.github/workflows/call_publish_static_assets.yml
    name: DEV Selfcare Infra Release static assets
    if: ${{ inputs.env == 'dev' || github.event_name == 'push' }}
    secrets: inherit
    with:
      environment: dev
      environment_short: d
      agent: self-hosted
      storage_account_name: "weu${{ inputs.domain || 'ar' }}checkoutst01"
      profile_name: "weu-${{ inputs.domain || 'ar' }}-checkout-afd-01"
      endpoint_name: "weu-${{ inputs.domain || 'ar' }}-checkout-fde-01"
      resource_group_name: "${{ (inputs.domain || 'ar') == 'ar' && 'checkout-fe-rg' || 'weu-pnpg-checkout-fe-rg' }}"
      domain: ${{ inputs.domain || 'ar' }}

  release_uat:
    uses: ./.github/workflows/call_publish_static_assets.yml
    name: UAT Selfcare Infra Release static assets
    if: ${{ inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      environment_short: u
      agent: self-hosted
      storage_account_name: "weu${{ inputs.domain }}checkoutst01"
      profile_name: "weu-${{ inputs.domain }}-checkout-afd-01"
      endpoint_name: "weu-${{ inputs.domain }}-checkout-fde-01"
      resource_group_name: "${{ inputs.domain == 'ar' && 'checkout-fe-rg' || 'weu-pnpg-checkout-fe-rg' }}"
      domain: ${{ inputs.domain }}

  release_prod:
    uses: ./.github/workflows/call_publish_static_assets.yml
    name: PROD Selfcare Infra Release static assets
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      environment_short: p
      agent: self-hosted
      storage_account_name: "weu${{ inputs.domain }}checkoutst01"
      profile_name: "weu-${{ inputs.domain }}-checkout-afd-01"
      endpoint_name: "weu-${{ inputs.domain }}-checkout-fde-01"
      resource_group_name: "${{ inputs.domain == 'ar' && 'checkout-fe-rg' || 'weu-pnpg-checkout-fe-rg' }}"
      domain: ${{ inputs.domain }}