name: Release App
run-name: Release ${{ inputs.app }} (${{ inputs.env }} - ${{ inputs.target }})

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options:
          - dev
          - uat
          - prod
        required: true
      target:
        type: choice
        description: Target type
        options:
          - ar
          - pnpg
        required: true
        default: ar
      app:
        type: choice
        description: App name
        options:
          - auth
          - iam
          - document-ms
          - onboarding-bff
          - onboarding-cdc
          - onboarding-ms
          - product
          - product-cdc
          - registry-proxy
          - user-ms
          - user-group-ms
          - user-cdc
          - user-group-cdc
          - institution-ms
          - delegation-cdc
          - institution-send-mail-scheduler
          - webhook
        required: true
        default: auth

jobs:
  release:
    uses: ./.github/workflows/call_release_app.yml
    name: Call Release App
    secrets: inherit
    with:
      env: ${{ inputs.env }}
      target: ${{ inputs.target }}
      app: ${{ inputs.app }}
      APP_PATH: apps/${{ inputs.app }}
      APPS_POM: apps/pom.xml
      POM: pom.xml
