name: Publish Cert Infra

permissions:
  contents: read
  id-token: write
  pull-requests: write

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - 'infra/cert/**'

  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: 'Select the Environment'
        default: dev
        options:
          - dev
          - uat
          - prod
      domain:
        required: true
        type: choice
        description: 'Select the Domain'
        default: ar
        options:
          - ar
          - pnpg

jobs:

  release_dev:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: "DEV ${{ inputs.domain || 'ar' }} Cert Infra Release"
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev-${{ inputs.domain || 'ar' }}
      base_path: infra/cert
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}

  release_uat:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: "UAT ${{ inputs.domain }} Cert Infra Release"
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat-${{ inputs.domain || 'ar' }}
      base_path: infra/cert
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}

  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: "PROD ${{ inputs.domain }} Cert Infra Release"
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod-${{ inputs.domain || 'ar' }}
      base_path: infra/cert
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}
