name: Run code review infra

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Module
        options:
          - dev
          - uat
          - prod

jobs:

  code_review_dev:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: '[Dev] Code review cert'
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev
      dir: 'infra/cert'
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

