name: Code Review - Cert Infra

permissions:
  contents: read
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        description: 'Select the Environment'
        default: dev
        options:
          - dev
          - uat
          - prod
      domain:
        required: true
        type: choice
        description: 'Select the Domain'
        default: ar
        options:
          - ar
          - pnpg

  pull_request:
    branches:
      - main
      - releases/*
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - 'infra/cert/**'
      - '.github/workflows/run_code_review_cert_infra.yml'

jobs:

  plan:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: "${{ inputs.env }}-${{ inputs.domain }} Cert Infra Plan"
    if: ${{ !startsWith(github.ref_name, 'releases/') }}
    secrets: inherit
    with:
      environment: ${{ inputs.env }}-${{ inputs.domain }}
      base_path: infra/cert
      use_private_agent: true
      override_github_environment: ${{ inputs.env }}
      use_labels: true
      override_labels: ${{ inputs.env }}

