name: Run code review infra

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev-ar
          - dev-pnpg
          - uat-ar
          - uat-pnpg
          - prod-ar
          - prod-pnpg
jobs:

  code_review:
    uses: ./.github/workflows/call_code_review_infra.yml
    name: 'Code review cert'
    secrets: inherit
    with:
      environment: ${{ startsWith(inputs.environment, 'dev') && 'dev' || startsWith(inputs.environment, 'uat') && 'uat' || 'prod' }}
      tf_environment: ${{ inputs.environment }}
      dir: infra/cert/${{ inputs.environment }}

