name: Run release Cert Infra

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - './infra/cert/**'

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev-ar
          - dev-pnpg
          - uat-ar
          - uat-pnpg
          - prod-ar
          - prod-pnpg

jobs:

  release_dev_ar:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Dev AR] Run Cert Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.environment == null) || inputs.environment == 'dev-ar' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-ar
      dir: ./infra/cert/dev-ar

  release_dev_pnpg:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Dev PNPG] Run Cert Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.environment == null) || inputs.environment == 'dev-pnpg' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: ./infra/cert/dev-pnpg

  release_uat_ar:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[UAT AR] Run Cert Infra Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.environment == null) || inputs.environment == 'uat-ar' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat-ar
      dir: ./infra/cert/uat-ar

  release_uat_pnpg:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[UAT PNPG] Run Cert Infra Release'
    if: ${{ inputs.environment == 'uat-pnpg' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat-pnpg
      dir: ./infra/cert/uat-pnpg

  release_prod_ar:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Prod AR] Run Cert Infra Release'
    if: ${{ inputs.environment == 'prod-ar' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod-ar
      dir: ./infra/cert/prod-ar

  release_prod_pnpg:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Prod PNPG] Run Cert Infra Release'
    if: ${{ inputs.environment == 'prod-pnpg' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod-pnpg
      dir: ./infra/cert/prod-pnpg
